name: Build Ameba Project

on:
  pull_request:
    branches:
      - master

jobs:
  build-amebalite-project-B1:
    uses: ./.github/workflows/build_template_amebalite.yml
    with:
      module_name: AMEBALITE
      artifacts_name: amebalite-B1
    secrets: inherit

  build-amebalite-project-B2:
    uses: ./.github/workflows/build_template_amebalite.yml
    with:
      module_name: AMEBALITE
      artifacts_name: amebalite-B2
    secrets: inherit

  build-amebalite-project-B3:
    uses: ./.github/workflows/build_template_amebalite.yml
    with:
      module_name: AMEBALITE
      artifacts_name: amebalite-B3
    secrets: inherit

  build-amebalite-project-B4:
    uses: ./.github/workflows/build_template_amebalite.yml
    with:
      module_name: AMEBALITE
      artifacts_name: amebalite-B4
    secrets: inherit

  build-amebalite-project-B5:
    uses: ./.github/workflows/build_template_amebalite.yml
    with:
      module_name: AMEBALITE
      artifacts_name: amebalite-B5
    secrets: inherit

  build-amebalite-project-B6:
    uses: ./.github/workflows/build_template_amebalite.yml
    with:
      module_name: AMEBALITE
      artifacts_name: amebalite-B6
    secrets: inherit

  build-amebasmart-project-B1:
    uses: ./.github/workflows/build_template_amebasmart.yml
    with:
      module_name: AMEBASMART
      artifacts_name: amebasmart-B1
    secrets: inherit

  build-amebasmart-project-B2:
    uses: ./.github/workflows/build_template_amebasmart.yml
    with:
      module_name: AMEBASMART
      artifacts_name: amebasmart-B2
    secrets: inherit

  build-amebasmart-project-B3:
    uses: ./.github/workflows/build_template_amebasmart.yml
    with:
      module_name: AMEBASMART
      artifacts_name: amebasmart-B3
    secrets: inherit

  build-amebasmart-project-B4:
    uses: ./.github/workflows/build_template_amebasmart.yml
    with:
      module_name: AMEBASMART
      artifacts_name: amebasmart-B4
    secrets: inherit

  build-amebasmart-project-B5:
    uses: ./.github/workflows/build_template_amebasmart.yml
    with:
      module_name: AMEBASMART
      artifacts_name: amebasmart-B5
    secrets: inherit

  build-amebasmart-project-B6:
    uses: ./.github/workflows/build_template_amebasmart.yml
    with:
      module_name: AMEBASMART
      artifacts_name: amebasmart-B6
    secrets: inherit

  build-amebadplus-project-B1:
    uses: ./.github/workflows/build_template_amebadplus.yml
    with:
      module_name: AMEBADPLUS
      artifacts_name: amebadplus-B1
    secrets: inherit

  build-amebadplus-project-B2:
    uses: ./.github/workflows/build_template_amebadplus.yml
    with:
      module_name: AMEBADPLUS
      artifacts_name: amebadplus-B2
    secrets: inherit

  build-amebadplus-project-B3:
    uses: ./.github/workflows/build_template_amebadplus.yml
    with:
      module_name: AMEBADPLUS
      artifacts_name: amebadplus-B3
    secrets: inherit

  build-amebadplus-project-B5:
    uses: ./.github/workflows/build_template_amebadplus.yml
    with:
      module_name: AMEBADPLUS
      artifacts_name: amebadplus-B5
    secrets: inherit

  build-amebadplus-project-B6:
    uses: ./.github/workflows/build_template_amebadplus.yml
    with:
      module_name: AMEBADPLUS
      artifacts_name: amebadplus-B6
    secrets: inherit